services:
  typesense:
    image: typesense/typesense:29.0
    container_name: typesense-dev
    restart: unless-stopped
    ports:
      - "8108:8108"
    environment:
      TYPESENSE_API_KEY: xyz
    volumes:
      - ./typesense-data:/data
    command: >
      --data-dir /data
      --api-key=${TYPESENSE_API_KEY}
      --enable-cors
  typesense_dashboard:
    image: ghcr.io/bfritscher/typesense-dashboard:2.4.3
    container_name: typesense_dashboard
    ports:
      - "3005:80"
    environment:
      TYPESENSE_SERVER_URL: "http://typesense:8108"
      TYPESENSE_API_KEY: "xyz"
    depends_on:
      - typesense