apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-expose-headers: "Set-Cookie"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 20m

spec:
  ingressClassName: nginx
  rules:
    - host: ""
      http:
        paths:       
          - path: /api/query/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-query
                port:
                  number: 3000
          - path: /api/hunter/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-hunter
                port:
                  number: 3001         
          - path: /api/slave/slave-0/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-slave-0
                port:
                  number: 8002         
          - path: /api/slave/slave-1/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-slave-1
                port:
                  number: 8002        
          - path: /api/slave/slave-2/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-slave-2
                port:
                  number: 8002                                     
          - path: /api/slave/slave-3/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-slave-3
                port:
                  number: 8002                      
          - path: /api/slave/slave-4/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-slave-4
                port:
                  number: 8002                    
          - path: /api/slave/slave-5/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-slave-5
                port:
                  number: 8002    
          - path: /api/slave/slave-6/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-slave-6
                port:
                  number: 8002                          
          - path: /api/slave/slave-7/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-slave-7
                port:
                  number: 8002 
          - path: /api/slave/slave-8/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-slave-8
                port:
                  number: 8002       
          - path: /api/slave/slave-9/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-slave-9
                port:
                  number: 8002       
          - path: /api/slave/slave-10/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-slave-10
                port:
                  number: 8002                                           