apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  REDIS_MAIN_HOST: "redis://redis-main:6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slave-config
data:
  DATABASE_HOST: "mysql"
  DATABASE_PORT: "3306"
  DATABASE_NAME: "service_slave"
  DATABASE_USER: "blacker"
  
