apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave-2
  labels:
    role: slave-2
spec:
  replicas: 1
  selector:
    matchLabels:
      role: slave-2
  template:
    metadata:
      labels:
        role: slave-2
    spec:
      containers:
        - name: service-slave
          image: pairfy/service-slave
          envFrom:
            - configMapRef:
                name: slave-config       
            - configMapRef:
                name: redis-config                     
          env:
            - name: NODE_ENV
              value: "development"
            - name: SLAVE_NAME
              value: "slave-2"
            - name: MARKET
              value: "forex"              
            - name: SYMBOL
              value: "USDJPY"
            - name: INTERVAL
              value: "30m"
            - name: SIDE
              value: "LONG"          
            - name: ACCOUNT_BALANCE
              value: "10000"               
            - name: ACCOUNT_RISK
              value: "0.5"                          
            - name: STOP_LOSS
              value: "1.0"
            - name: TAKE_PROFIT
              value: "6.9"              
            - name: CONTRACT_SIZE
              value: "100000"
            - name: PRECISION
              value: "3"              
            - name: SHOW_PLOTS
              value: "false"              
            - name: DESCRIPTION
              value: "RSI,ADX,MFI"  
            - name: MARKET_HOST
              value: "http://service-market:8001"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password-secret
                  key: password
                                    
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: slave-storage
              mountPath: /app/output
      volumes:
        - name: slave-storage
          persistentVolumeClaim:
            claimName: pvc-slave-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-slave-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: service-slave-2
spec:
  selector:
    role: slave-2
  ports:
    - name: http
      protocol: TCP
      port: 8002
      targetPort: 8002
