apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave-3
  labels:
    role: slave-3
spec:
  replicas: 1
  selector:
    matchLabels:
      role: slave-3
  template:
    metadata:
      labels:
        role: slave-3
    spec:
      containers:
        - name: service-slave
          image: pairfy/service-slave
          envFrom:
            - configMapRef:
                name: slave-config       
            - configMapRef:
                name: redis-config                     
          env:
            - name: NODE_ENV
              value: "development"
            - name: SERVICE_NAME
              value: "slave-3"  
            - name: SLAVE_NAME
              value: "slave-3"
            - name: SYMBOL
              value: "XRPUSDT"
            - name: LEVERAGE
              value: "5"
            - name: STOP_LOSS
              value: "0.96"
            - name: MARGIN_TYPE
              value: "ISOLATED"
            - name: ORDER_AMOUNT
              value: "500"
            - name: SHOW_PLOTS
              value: "false"
            - name: DESCRIPTION
              value: "RSI,Squeeze,ADX,Heikin"  
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password-secret
                  key: password
            - name: BINANCE_KEY
              valueFrom:
                secretKeyRef:
                  name: binance-key-secret
                  key: key
            - name: BINANCE_SECRET
              valueFrom:
                secretKeyRef:
                  name: binance-secret-secret
                  key: secret
                                    
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: slave-storage
              mountPath: /app/output
      volumes:
        - name: slave-storage
          persistentVolumeClaim:
            claimName: pvc-slave-3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-slave-3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: service-slave-3
spec:
  selector:
    role: slave-3
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
