name: service-slave

on:
  push:
    branches:
      - main
    paths:
      - 'backend/service-slave/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t pairfy/service-slave ./backend/service-slave

      - name: Push Docker image
        run: docker push pairfy/service-slave

      - name: Set up DigitalOcean CLI
        uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{ secrets.CLOUD_API }}

      - name: Set up kubeconfig
        run: doctl kubernetes cluster kubeconfig save k9blacker

      - name: Delete all slave deployments and reapply manifests
        run: |
          echo "ğŸ” Searching deployments..."
          deployments=$(kubectl get deployments -o name | grep 'slave-' || true)

          if [ -z "$deployments" ]; then
            echo "âš ï¸ No deployments slave-"
          else
            echo "ğŸ—‘ï¸ Deleting deployments slave-..."
            for dep in $deployments; do
              echo "  - Deleting $dep"
              kubectl delete "$dep" --ignore-not-found=true
            done
          fi

          sleep 1m

          echo "ğŸ“¦ Applying deployments..."
          kubectl apply -f backend/A/k8s-prod

          echo "âœ… Finished"

