name: service-market

on:
  push:
    branches:
      - main
    paths:
      - 'backend/service-market/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t pairfy/service-market ./backend/service-market

      - name: Push Docker image
        run: docker push pairfy/service-market

      - name: Set up DigitalOcean CLI
        uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{ secrets.CLOUD_API }}

      - name: Set up kubeconfig
        run: doctl kubernetes cluster kubeconfig save k9blacker

      - name: Restart Kubernetes deployment
        run: kubectl rollout restart deployment service-market