name: service-slave

on:
  push:
    branches:
      - main
    paths:
      - 'backend/service-slave/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t pairfy/service-slave ./backend/service-slave

      - name: Push Docker image
        run: docker push pairfy/service-slave

      - name: Set up DigitalOcean CLI
        uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{ secrets.CLOUD_API }}

      - name: Set up kubeconfig
        run: doctl kubernetes cluster kubeconfig save k9blacker

      - name: Restart slave deployments gradually (dynamic)
        run: |
          kubectl get deployments -o name | grep 'slave-' | while read dep; do
            echo "üîÑ Restart $dep ..."
            kubectl rollout restart "$dep"

            echo "‚è≥ Waiting $dep ..."
            kubectl rollout status "$dep" --timeout=300s

            echo "‚úÖ Completed $dep"
            echo ""
          done
